from . import res_partner
from . import product
from . import sale_order
from . import ro_warranty
from . import ro_installation
from . import ro_amc
from . import ro_service
from . import dashboard
from . import ro_product_extension