[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = peanutsquare


db_host = db
db_user = sas
db_password = sas
; PRODUCTION PERFORMANCE TUNING
; Workers: Generally (CPU Cores * 2) + 1. 
; Example: For a 2 Core server, set workers = 5. Set to 0 for debugging.
workers = 4

; LOGGING
logfile = /var/log/odoo/odoo.log
log_level = info

; NETWORKING
; Set to True if you are using Nginx/Apache as a reverse proxy (Recommended for SSL)
proxy_mode = True